In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\shrawan\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shrawan\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shrawan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shrawan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shrawan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shrawan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Pandas

In [3]:
# Install pandas

In [4]:
import pandas as pd

In [5]:
s = pd.Series([10,20,30])

In [6]:
s

0    10
1    20
2    30
dtype: int64

In [7]:
type(s)

pandas.core.series.Series

In [8]:
s = pd.Series([10,20,30],index=['a','b','c'])

In [9]:
s

a    10
b    20
c    30
dtype: int64

In [10]:
student = {
    "name":"Shrawan",
    "age":19,
    "marks":71
}

In [11]:
print(student)

{'name': 'Shrawan', 'age': 19, 'marks': 71}

In [12]:
s = pd.Series(student)

In [13]:
s

name     Shrawan
age           19
marks         71
dtype: object

In [14]:
s = pd.Series(5,index = [0,1,2,3,4])

In [15]:
s

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [16]:
# Attributes

In [17]:
s = pd.Series([10,20,30],index = ['a','b','c'])

In [18]:
s

a    10
b    20
c    30
dtype: int64

In [19]:
s.values

array([10, 20, 30])

In [20]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [21]:
s.dtype

dtype('int64')

In [22]:
s.shape

(3,)

In [23]:
s*2

a    20
b    40
c    60
dtype: int64

In [24]:
s = pd.Series([10,None,20])

In [25]:
s

0    10.0
1     NaN
2    20.0
dtype: float64

In [26]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [27]:
s.dropna()

0    10.0
2    20.0
dtype: float64

In [28]:
s

0    10.0
1     NaN
2    20.0
dtype: float64

In [29]:
s.fillna(5)

0    10.0
1     5.0
2    20.0
dtype: float64

In [30]:
s = pd.Series([1,2,2,3,3,3])

In [31]:
s

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [32]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [33]:
s = pd.Series([10,20,30,40],index = ['a','b','c','d'])

In [34]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [35]:
s['a']

np.int64(10)

In [36]:
s['b']

np.int64(20)

In [37]:
data = {
    "Roll_No":[100,200,300,400],
    "Name":["Omkar","Shrawan","Sarthak","Tanmay"],
    "Marks":[99,100,101,None]
}

In [38]:
data

{'Roll_No': [100, 200, 300, 400],
 'Name': ['Omkar', 'Shrawan', 'Sarthak', 'Tanmay'],
 'Marks': [99, 100, 101, None]}

In [40]:
df = pd.DataFrame(data)

In [41]:
df

   Roll_No     Name  Marks
0      100    Omkar   99.0
1      200  Shrawan  100.0
2      300  Sarthak  101.0
3      400   Tanmay    NaN

In [42]:
data = {
    "Subjects":['OOP','Java','Python','DSU'],
    "Marks":[90,98,89,88],
    "Grade":[89,90,87,80]
}

In [43]:
df = pd.DataFrame(data)

In [44]:
df

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [45]:
df.to_csv('Marks_data.csv',index = False)

In [46]:
df = pd.read_csv("Marks_data.csv")

In [47]:
df

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [48]:
df.head()

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [49]:
df.tail()

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [50]:
df.shape

(4, 3)

In [51]:
df.columns

Index(['Subjects', 'Marks', 'Grade'], dtype='object')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Subjects  4 non-null      object
 1   Marks     4 non-null      int64
 2   Grade     4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [53]:
df.describe()

           Marks     Grade
count   4.000000   4.00000
mean   91.250000  86.50000
std     4.573474   4.50925
min    88.000000  80.00000
25%    88.750000  85.25000
50%    89.500000  88.00000
75%    92.000000  89.25000
max    98.000000  90.00000

In [54]:
df.isnull().sum()

Subjects    0
Marks       0
Grade       0
dtype: int64

In [55]:
df = df.drop_duplicates()

In [56]:
df

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [57]:
df['Marks'] = df['Marks'].astype(int)

In [58]:
df

  Subjects  Marks  Grade
0      OOP     90     89
1     Java     98     90
2   Python     89     87
3      DSU     88     80

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Subjects  4 non-null      object
 1   Marks     4 non-null      int64
 2   Grade     4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [60]:
df["Subjects"]

0       OOP
1      Java
2    Python
3       DSU
Name: Subjects, dtype: object

In [61]:
df[["Subjects","Marks"]]

  Subjects  Marks
0      OOP     90
1     Java     98
2   Python     89
3      DSU     88

In [62]:
df=df.sort_values(by="Marks",ascending=False)

In [63]:
df

  Subjects  Marks  Grade
1     Java     98     90
0      OOP     90     89
2   Python     89     87
3      DSU     88     80